
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/teaching_app?serverTimezone=Europe/Budapest
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

